### ISSUE TITLE
404 links in README.md

### ISSUE THREAD

**Issue by alixeb** [paritytech/js-libs#1]
A lot of links in REAME.md (if not all) give 404 star wars page

**Comment by amaurymartiny** [comment]
Hey Alixe, thanks for checking out this repo. It's currently under heavy development, the idea is that it will host a lerna monorepo of Parity's JS libs, all in Typescript, all tested and documented, as briefly described here: https://github.com/paritytech/fether/issues/122.

I'm making some progress, but until it's ready, the links will unfortunately remain dead.
