### ISSUE TITLE
Broken API links in Light.js API Docs

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/js-libs#146]
When I go to the [Light.js package](https://github.com/paritytech/js-libs/tree/master/packages/light.js) I can click [Full Documentation](https://paritytech.github.io/js-libs/light.js/) and it takes me to the API Docs.

But when I scroll down the menu and try to click any of the API links (see screenshot below), they are all broken. The temporary fallback is to view the [SUMMARY.md](https://github.com/paritytech/js-libs/blob/master/packages/light.js/docs/api/SUMMARY.md) file that contains the same links:

<img width="705" alt="screen shot 2019-02-04 at 6 37 16 pm" src="https://user-images.githubusercontent.com/6226175/52195462-2f073c00-28ac-11e9-9a2d-f51ee3e0de60.png">

**Comment by amaurymartiny** [comment]
Ah... you're right. It *might* be solved by adding a `.nojekyll` file [here](https://github.com/paritytech/js-libs/tree/gh-pages/light.js).
