### ISSUE TITLE
Remove withoutLoading()?

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/js-libs#154]
TransactionCount$ is an Observable that fires

* `nonce1, Symbol('LOADING'), nonce2, Symbol('LOADING'), nonce3...` by default
* `nonce1, nonce2, nonce3...` when you add withoutLoading()

where `Symbol('LOADING')` represents the RPC call to the network being made.

After seeing people use it, it seems like it creates some confusion:
- most of the apps don't need the `Symbol('LOADING')` state, so there's a lot of `withoutLoading()` hanging in the app
- some RPC observables (balanceOf$, transactionCount$...) have `Symbol('LOADING')`, while others don't (account$, blockNumber$...). Only the ones that need to make an additional RPC call to the network have a `Symbol('LOADING')` state.

It might be simpler to just remove it completely.

**Comment by axelchalon** [comment]
I agree! Let's remove it and make it the default
