### ISSUE TITLE
Update required to check for Parity Path in new locations 

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/js-libs#210]
Currently we are checking the Parity Path in the following locations in `isParityInOs` function: https://github.com/paritytech/js-libs/blob/master/packages/electron/src/getParityPath.ts#L58

However in newer versions the Parity Ethereum path is in different locations depending on the OS. See locations mentioned in the Fether wiki here https://github.com/paritytech/wiki/pull/312

**Comment by axelchalon** [comment]
These locations of Parity Ethereum are unique to Fether, we shouldn't check for them in js-libs. In the newer version of Fether we directly pass the path to the binary to the js-libs functions (https://github.com/paritytech/js-libs/pull/205 `Add parityPath to the options of runParity and signerNewToken`).
