### ISSUE TITLE
Unable to connect via IPC

### ISSUE THREAD

**Issue by ethernomad** [paritytech/js-libs#219]
With web3.js I can connect via IPC, but with this library I can only connect with HTTP

This works:
`
parityApi = new Api(new Api.Provider.Http('http://localhost:8545'))
`

This does not:
`
parityApi = new Api(new Api.Provider.Ipc(ipcPath))
`

**Comment by axelchalon** [comment]
Hi,

We don't support connecting to Parity Ethereum using IPC.

`Api.Provider.Ipc` was used for communicating with IPC between an Electron webview and the Electron main process (sorry for the ambiguous naming!).

**Comment by amaurymartiny** [comment]
Hey @ethernomad! Unfortunately the IPC provider was only created to support the (now defunct) [Parity UI](https://github.com/parity-js/shell) in *an Electron context* (see their ipcMain & ipcRenderer docs), so it might not work out-of-the-box with other projects.

However PRs are very welcome! The [ipc.js](https://github.com/paritytech/js-libs/blob/master/packages/api/src/provider/ipc.js) itself is not that big, and it should be fairly doable to support IPC more generally.

**Comment by ethernomad** [comment]
I should have mentioned that I am using it in an Electron app. Is connecting via IPC supposed to be working at the moment in Electron? My project uses web3.js to talk to Parity via IPC. I just use @parity/api to access some Parity APIs that web3.js doesn't support.

**Comment by amaurymartiny** [comment]
> Is connecting via IPC supposed to be working at the moment in Electron?

Then it should, have a look at https://github.com/parity-js/shell/pull/8 for a working demo. But also note that we decided **not** to use IpcProvider because of security reasons, Electron IPC messages don't work in renderer processes if contextIsolation is true (which is recommended).
