### ISSUE TITLE
Drop pubsub subscription after X seconds without any subscribers

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/js-libs#45]
Now:

- a subscriber subscribes to onEveryBlock$
- a pubsub connection is created to `eth_blockNumber`
- the subscriber unsubscribes
- refCount = 0 drops the pubsub connection immediately
- the subscriber resubscribes
- a new pubsub connection is created

Ideal:
- a subscriber subscribes to onEveryBlock$
- a pubsub connection is created to `eth_blockNumber`
- the subscriber unsubscribes
- refCount = 0, wait for X seconds before dropping the pubsub connection
- before X seconds passed, the subscriber resubscribes
- the same pubsub connection is used
- the subscriber unsubscribes
- After X seconds, no new subscriber, the pubsub connection drops

**Comment by axelchalon** [comment]
> * a subscriber subscribes to onEveryBlock$
> * a pubsub connection is created to eth_blockNumber

for the record, tracking issue for that part is here https://github.com/paritytech/js-libs/issues/19
