### ISSUE TITLE
@parity/api npmjs page leads to a wrong github project

### ISSUE THREAD

**Issue by JohnnySheffield** [paritytech/js-libs#46]
Hi!

There is currently a confusing situation regarding @parity/api repos:

When you visit [@parity/api npmjs page](https://www.npmjs.com/package/@parity/api) there is a github link leading you to [paritytech/js-api](https://github.com/paritytech/js-api) repo where you are notified that the repo is moved to [Parity-JS/api](https://github.com/Parity-JS/api)

edit: found this issue mentioned in https://github.com/paritytech/js-libs/blob/master/packages/api/docs/CHANGELOG-3.0.md

**Comment by amaurymartiny** [comment]
Yes, this is bugging me too. I want to do it in the correct order:
- convert @parity/api to TS: https://github.com/paritytech/js-libs/issues/21
- then update the package on npm

**Comment by amaurymartiny** [comment]
Fixed.
