### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/js-libs#78]
When I try to run the unit tests with `yarn run test` using Node.js version v10.6.0 it gave me the following error:
```
error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".
```

And when I try switching to a more recent version of Node.js v11.1.0 with `nvm use v11.1.0`, it gives error:
```
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/lib/config/core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (/Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/lib/config/core.js:411:12)
    at parseField (/Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/lib/config/core.js:389:7)
    at /Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/lib/config/core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (/Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/lib/config/core.js:328:23)
    at ConfigChain.addString (/Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/lib/config/core.js:316:10)
    at /Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
/Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/lib/npm.js:61
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/lib/npm.js:61:13)
    at process.errorHandler (/Users/me/.nvm/versions/node/v11.1.0/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:628:27)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `npm config delete prefix` or `nvm use --delete-prefix v11.1.0` to unset it.
```

Creating a .env file containing `NPM_TOKEN=...` produces the same error. 
How do we run the tests? What value of `NPM_TOKEN` should we use?

**Comment by axelchalon** [comment]
Can reproduce (v11.0.0). Seems to be an issue with nvm. I can make it work with `export NPM_TOKEN=""; nvm use v11.0.0`

**Comment by ltfschoen** [comment]
Great, shall we add that to a "Contributing => Testing" or similar section of the Readme?

**Comment by ltfschoen** [comment]
@amaurymartiny It looks like we just have to add `https` instead of `http` (i.e. `- npm set registry "https://registry.npmjs.org/:_authToken=$NPM_TOKEN"`)

In the [failed build](https://travis-ci.org/paritytech/js-libs/builds/473807579), within the "Deploying application" section, it shows the 401 error that you mentioned as shown below:

<img width="401" alt="screen shot 2019-01-01 at 4 12 27 pm" src="https://user-images.githubusercontent.com/6226175/50570455-063ce400-0de0-11e9-907f-a7ed4e94b8ab.png">

<img width="957" alt="screen shot 2019-01-01 at 4 11 34 pm" src="https://user-images.githubusercontent.com/6226175/50570454-ee656000-0ddf-11e9-98b4-6bb1409f8057.png">

In the [successful build](https://travis-ci.org/paritytech/js-libs), within the "Deploying application" section it returns 200 since it prefixes "//registry.npmjs.org/:_authToken=$NPM_TOKEN" with `https` as shown below:

<img width="496" alt="screen shot 2019-01-01 at 4 13 33 pm" src="https://user-images.githubusercontent.com/6226175/50570461-63389a00-0de0-11e9-8dc0-6a6f51d1f12d.png">

<img width="612" alt="screen shot 2019-01-01 at 4 14 59 pm" src="https://user-images.githubusercontent.com/6226175/50570463-751a3d00-0de0-11e9-9cd2-2abc1b7efc7f.png">

**Comment by ltfschoen** [comment]
@amaurymartiny I've created this PR https://github.com/paritytech/js-libs/pull/86 with the proposed change to see if it builds successfully

**Comment by amaurymartiny** [comment]
@ltfschoen Unfortunately https://travis-ci.org/paritytech/js-libs/builds/474326384#L1386.

I'm reverting #86.
